spring.application.name=api-gateway-samStore
server.port=8080

spring.config.import=optional:configserver:http://localhost:8888

spring.cloud.config.fail-fast=false
spring.cloud.config.retry.initial-interval=5000
spring.cloud.config.retry.max-attempts=20
spring.cloud.config.retry.multiplier=1.5