spring.application.name=category-service
server.port=9090


spring.datasource.url=jdbc:mysql://localhost:3308/sam-db
spring.datasource.username=root
spring.datasource.password=root

###################
##CUSTOM SETTINGS##
###################
app.queue.name=log-queue

eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}
