version: "3.9"

services:
    mysql-category:
      image: mysql:8.0
      container_name: mysql-category-db
      ports:
        - "3308:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: category_db
      volumes:
        - mysql-category-data:/var/lib/mysql
        - ../../util/script/init-script-category-db.sql:/docker-entrypoint-initdb.d/init.sql:ro

    mysql-product:
      image: mysql:8.0
      container_name: mysql-producto-db
      ports:
        - "3309:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: product_db
      volumes:
        - mysql-product-data:/var/lib/mysql
        - ../../util/script/init-script-product-db.sql:/docker-entrypoint-initdb.d/init.sql:ro

    mysql-user:
      image: mysql:8.0
      container_name: mysql-user-db
      ports:
        - "3310:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: user_db
      volumes:
        - mysql-user-data:/var/lib/mysql
        - ../../util/script/init-script-user-db.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  mysql-category-data:
  mysql-product-data:
  mysql-user-data:
